# https://hub.docker.com/r/moodlehq/moodle-php-apache/
# set .env vars: DOMAIN_NAME , SITE_PATH

version: '3'

services:
  webserver:
    image: moodlehq/moodle-php-apache:8.2-bullseye
    container_name: "moodle_${SITE_PATH}"
    environment:
      - DOMAIN_NAME
      - SITE_PATH
    labels:
      - traefik.enable=true
      - traefik.http.services.moodle_${SITE_PATH}.loadbalancer.server.port=80
      - traefik.http.routers.moodle_${SITE_PATH}.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.moodle_${SITE_PATH}.rule=Host(`${DOMAIN_NAME}`) && ( PathPrefix(`/${SITE_PATH}`) )
      - traefik.http.middlewares.moodle_${SITE_PATH}.stripprefix.prefixes=/${SITE_PATH}    
      - traefik.http.middlewares.moodle_${SITE_PATH}.stripprefix.forceslash=true
      - traefik.http.routers.moodle_${SITE_PATH}.middlewares=moodle_${SITE_PATH}
     
      
      
 








      

      
    volumes:
      - moodledata:/var/moodledata
    restart: unless-stopped
    networks: 
      - proxy_default

volumes:
  moodledata:

networks:
  proxy_default:
    external: true
